### ISSUE TITLE
Extend Readme to include "using selectors section"

### ISSUE THREAD

**Issue by eimerreis** [orizens/ngrx-styleguide#1]
at the "Reducers Included Files" you placed a ".selectors" file in the folder structure.

```
- src
  - app
    - core
      - store
        - now-playing
          - index.ts
          - now-playing.reducer.ts
          - now-playing.spec.ts
          - now-playing.actions.ts
          - now-playing.selectors.ts
``` 

 I'd really appreciate if you'd show an example of that kind of file

**Comment by orizens** [comment]
hi @eimerreis 
please view https://github.com/orizens/echoes-player/blob/master/src/app/core/store/now-playlist/now-playlist.selectors.ts
