### ISSUE TITLE
Chunking the core

### ISSUE THREAD

**Issue by EvanBurbidge** [orizens/ngrx-styleguide#3]
I love this style guide, this is not an issue more a question, when using Angular Cli in order to generate a project I feel that the core / main.js bundle is going to start getting to large do you have any ideas on how to get around the Angular cli config in order to have a separate file for the core module code?

**Comment by orizens** [comment]
angular-cli should support now module splitting.

**Comment by orizens** [comment]
feels like this has been resolved by ngcli.
please open a new issue if otherwise.
